Importing Libraries and Data

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
data = pd.read_csv(r"C:\Users\anirv\Downloads\flipkart.csv")
print(f"Data Loaded: {data.shape[0]} rows, {data.shape[1]} columns")

Data Loaded: 80000 rows, 25 columns

In [62]:
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
data_backup = data.copy()

In [4]:
data.head()

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,review_count,stock_available,units_sold,listing_date,delivery_days,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,26975,267,66,2022-04-12,11,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,45848,16,2703,2023-05-14,3,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,5138,806,2394,2022-09-13,5,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,2000,509,1732,2019-08-05,1,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,25801,809,4644,2018-08-26,7,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90

Data Preprocessing

In [5]:
data.columns.str.strip()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          80000 non-null  object
 1   product_name        80000 non-null  object
 2   category            80000 non-null  object
 3   brand               80000 non-null  object
 4   seller              80000 non-null  object
 5   seller_city         80000 non-null  object
 6   price               80000 non-null  float64
 7   discount_percent    80000 non-null  int64
 8   final_price         80000 non-null  float64
 9   rating              80000 non-null  float64
 10  review_count        80000 non-null  int64
 11  stock_available     80000 non-null  int64
 12  units_sold          80000 non-null  int64
 13  listing_date        80000 non-null  object
 14  delivery_days       80000 non-null  int64
 15  weight_g            80000 non-null  float64
 16  warranty_months     80000 non-null  int64
 17  color               80000 non-null  object
 18  size                66516 non-null  object
 19  return_policy_days  80000 non-null  int64
 20  is_returnable       80000 non-null  bool
 21  payment_modes       80000 non-null  object
 22  shipping_weight_g   80000 non-null  float64
 23  product_score       80000 non-null  float64
 24  seller_rating       80000 non-null  float64
dtypes: bool(1), float64(7), int64(7), object(10)
memory usage: 14.7+ MB

Drop Unnecessary Columns

In [6]:
data = data.drop(columns = ['weight_g','shipping_weight_g','seller_rating'],errors = 'ignore')
data = data.drop(columns = ['color','size'],errors = 'ignore')

In [7]:
data.columns

Index(['product_id', 'product_name', 'category', 'brand', 'seller',
       'seller_city', 'price', 'discount_percent', 'final_price', 'rating',
       'review_count', 'stock_available', 'units_sold', 'listing_date',
       'delivery_days', 'warranty_months', 'return_policy_days',
       'is_returnable', 'payment_modes', 'product_score'],
      dtype='object')

Installing required Libraries

In [8]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\anirv\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\anirv\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\anirv\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anirv\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [9]:
import pandas as pd
from sqlalchemy import create_engine

data = pd.read_csv(r"C:\Users\anirv\Downloads\flipkart.csv")

data.head()

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,review_count,stock_available,units_sold,listing_date,delivery_days,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,26975,267,66,2022-04-12,11,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,45848,16,2703,2023-05-14,3,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,5138,806,2394,2022-09-13,5,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,2000,509,1732,2019-08-05,1,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,25801,809,4644,2018-08-26,7,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90

Exporting data to MySQL

In [10]:
engine = create_engine("mysql+pymysql://root:root@localhost:3306/flipkart")

In [17]:
data.to_sql(name='analysis', con=engine, if_exists='replace', index=False)

80000

In [20]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS products;"))
    conn.execute(text("""
    CREATE TABLE products AS
    SELECT DISTINCT
        product_id,
        product_name,
        category,
        brand,
        color,
        size,
        weight_g,
        warranty_months
    FROM analysis;
    """))
    conn.commit()

In [21]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS sellers;"))
    conn.execute(text("""

    CREATE TABLE sellers AS
    SELECT DISTINCT
        seller,
        seller_city,
        seller_rating
    FROM analysis;
    """))
    conn.commit()

In [22]:
with engine.connect() as conn:
    # Step 1: Drop table
    conn.execute(text("DROP TABLE IF EXISTS orders;"))

    # Step 2: Create table
    conn.execute(text("""
        CREATE TABLE orders AS
        SELECT
            product_id,
            seller,
            price,
            discount_percent,
            final_price,
            units_sold,
            stock_available,
            listing_date
        FROM analysis;
    """))

    conn.commit()

In [23]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS reviews;"))

    conn.execute(text("""
    CREATE TABLE reviews AS
    SELECT
        product_id,
        rating,
        review_count,
        product_score
    FROM analysis;
    """))
    conn.commit()

In [24]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS logistics;"))

    conn.execute(text("""
    CREATE TABLE logistics AS
    SELECT
        product_id,
        delivery_days,
        shipping_weight_g,
        return_policy_days,
        is_returnable
    FROM analysis;
    """))
    conn.commit()

In [25]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS payments;"))
 
    conn.execute(text("""
    CREATE TABLE payments AS
    SELECT
        product_id,
        payment_modes
    FROM analysis;
    """))
    conn.commit()

In [88]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS returns;"))
 
    conn.execute(text("""
    CREATE TABLE returns AS
    SELECT
        product_id,
        return_policy_days,
        is_returnable
    FROM analysis;
    """))
    conn.commit()

In [89]:
pd.read_sql("SHOW TABLES;", con=engine)

  Tables_in_flipkart
0           analysis
1          logistics
2             orders
3           payments
4           products
5            returns
6            reviews
7            sellers

Analyzing Insights using Queries

 Revenue & Sales

In [61]:
#What are the top 10 products by total revenue?
pd.read_sql("""
SELECT 
    p.product_name,
    SUM(o.final_price * o.units_sold) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10
""", con=engine)

            product_name        revenue
0          HP Series 622 747,017,667.76
1        Apple Prime 418 689,491,818.22
2      Philips Ultra 569 641,760,465.79
3        Puma Edition 70 637,242,795.29
4          HP Series 569 618,875,673.79
5    Prestige Series 377 616,721,264.69
6  Whirlpool Edition 621 610,970,777.06
7       Apple Series 993 600,604,105.06
8          LG Series 980 595,264,395.93
9           LG Ultra 138 594,696,770.62

In [60]:
#Which categories generate the highest revenue?
pd.read_sql("""
SELECT 
    p.category,
    SUM(o.final_price * o.units_sold) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC
LIMIT 10;
""", con=engine)

         category            revenue
0            Toys 606,448,572,518.21
1          Beauty 605,815,988,795.83
2         Fashion 599,555,915,966.14
3     Electronics 599,487,883,202.69
4      Appliances 594,060,346,834.73
5          Sports 589,050,280,695.13
6         Mobiles 584,330,925,504.20
7  Home & Kitchen 583,158,043,408.51

In [59]:
#what is the highest revenue by city?
pd.read_sql("""
SELECT 
    seller_city,
    SUM(final_price * units_sold) AS total_revenue
FROM analysis
GROUP BY seller_city
ORDER BY total_revenue DESC;
""", con=engine)

  seller_city      total_revenue
0        Pune 612,219,860,530.03
1       Delhi 605,991,989,287.20
2     Chennai 603,016,019,007.65
3   Hyderabad 599,792,407,844.97
4      Mumbai 593,175,964,198.65
5   Ahmedabad 588,925,026,262.70
6   Bengaluru 580,293,631,550.33
7     Kolkata 578,493,058,243.91

In [164]:
#What is the average revenue per product/category?
pd.read_sql("""
SELECT 
    a.category,
    FORMAT(AVG(b.final_price * b.units_sold), 0) AS total_revenue
    FROM products a
    JOIN orders b ON
    a.product_id = b.product_id
    GROUP BY a.category
    ORDER BY total_revenue DESC
    LIMIT 5;
""", con=engine)

         category total_revenue
0          Beauty    60,017,435
1            Toys    59,742,742
2  Home & Kitchen    59,731,439
3     Electronics    59,638,667
4      Appliances    59,578,813

In [58]:
#How does revenue vary over time (monthly trend)?
pd.read_sql("""
select 
    p.category,
    date_format(o.listing_date, '%%Y-%%m') as month,
    round(sum(o.units_sold * o.price), 0) as revenue
from orders o
join products p
    on o.product_id = p.product_id
group by date_format(o.listing_date, '%%Y-%%m'), p.category
order by month desc
limit 10;
""", con=engine)

         category    month           revenue
0      Appliances  2023-06 10,774,832,644.00
1          Beauty  2023-06  7,931,289,763.00
2     Electronics  2023-06 11,343,641,985.00
3         Fashion  2023-06  8,718,268,364.00
4  Home & Kitchen  2023-06  8,517,639,808.00
5         Mobiles  2023-06  8,284,819,173.00
6          Sports  2023-06 10,152,819,297.00
7            Toys  2023-06 10,889,804,979.00
8      Appliances  2023-05 11,561,091,528.00
9          Beauty  2023-05 12,667,993,251.00

Demand vs Supply

In [38]:
#Which products have high demand but low stock?
pd.read_sql("""
SELECT 
    p.product_name,
    SUM(o.units_sold) AS total_units_sold,
    AVG(o.stock_available) AS avg_stock
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name
HAVING 
    SUM(o.units_sold) > 500   -- high demand threshold
    AND AVG(o.stock_available) < 50  -- low stock threshold
ORDER BY total_units_sold DESC
LIMIT 10;
""", con=engine)

        product_name  total_units_sold  avg_stock
0    Apple Ultra 802           12770.0    36.3333
1  Adidas Series 329            9347.0    48.5000
2     Puma Ultra 433            8850.0    21.5000
3  Reebok Series 852            8823.0    39.0000
4    Redmi Model 329            8322.0    49.5000
5    Redmi Model 117            8173.0    31.5000
6  Samsung Model 248            8135.0    45.5000
7     Puma Model 815            7949.0    49.0000
8    Redmi Model 921            7653.0    38.5000
9   Apple Series 229            7440.0    47.0000

In [43]:
#What is the demand-to-stock ratio for each product?
pd.read_sql("""
select 
    p.product_name as name,
    sum(o.units_sold) as total_demand,
    max(o.stock_available) as stock,
    round(sum(o.units_sold) / nullif(max(o.stock_available), 0), 2) as demand_to_stock
from orders o
join products p
    on p.product_id = o.product_id
group by p.product_name, p.product_id
order by demand_to_stock desc
limit 10;
""", con=engine)

                  name  total_demand  stock  demand_to_stock
0     Puma Edition 422        4914.0      1           4914.0
1      Adidas Prime 63        4881.0      1           4881.0
2       Puma Ultra 320        4851.0      1           4851.0
3      Dell Series 677        4807.0      1           4807.0
4         LG Prime 641        4729.0      1           4729.0
5        Nike Ultra 12        4729.0      1           4729.0
6         LG Prime 842        4592.0      1           4592.0
7  Whirlpool Model 132        4566.0      1           4566.0
8    Samsung Ultra 472        4457.0      1           4457.0
9       Puma Model 815        4363.0      1           4363.0

In [48]:
#Which categories are understocked or overstocked?
pd.read_sql("""
select 
    p.category,
    sum(o.units_sold) as total_demand,
    sum(o.stock_available) as total_stock,
    round(sum(o.units_sold) / nullif(sum(o.stock_available), 0), 2) as demand_to_stock_ratio,
    case 
        when sum(o.units_sold) > sum(o.stock_available) then 'understock'
        when sum(o.units_sold) < sum(o.stock_available) then 'overstock'
        else 'balanced'
    end as stock_status
from products p
join orders o
    on p.product_id = o.product_id
group by p.category
order by demand_to_stock_ratio desc;
""", con=engine)

,category,total_demand,total_stock,demand_to_stock_ratio,stock_status
0,Electronics,25372487.0,4997282.0,5.08,understock
1,Home & Kitchen,24663953.0,4872183.0,5.06,understock
2,Fashion,25182630.0,5011068.0,5.03,understock
3,Appliances,25184186.0,5006342.0,5.03,understock
4,Toys,25565969.0,5098237.0,5.01,understock
5,Sports,24792347.0,4957093.0,5.00,understock
6,Mobiles,24710378.0,4951682.0,4.99,understock
7,Beauty,25129312.0,5041654.0,4.98,understock

In [50]:
# Which categories are overstocked?
pd.read_sql("""
select 
    a.category,
    sum(b.units_sold) as demand,
    sum(b.stock_available) as stock,
    round(sum(b.units_sold) / sum(b.stock_available), 2) as demand_to_stock_ratio,
    case
        when sum(b.units_sold) < sum(b.stock_available) then 'overstock'
        else 'balanced'
    end as stock_status
from products a
join orders b
    on a.product_id = b.product_id
group by a.category,a.product_id
order by stock_status desc
limit 10;
""", con=engine)

     category  demand  stock  demand_to_stock_ratio stock_status
0      Beauty    41.0  901.0                   0.05    overstock
1     Fashion   615.0  909.0                   0.68    overstock
2  Appliances   195.0  640.0                   0.30    overstock
3     Fashion   357.0  669.0                   0.53    overstock
4     Mobiles   668.0  795.0                   0.84    overstock
5        Toys    26.0  425.0                   0.06    overstock
6     Mobiles   630.0  738.0                   0.85    overstock
7     Mobiles   139.0  724.0                   0.19    overstock
8      Sports   567.0  794.0                   0.71    overstock
9     Fashion   601.0  982.0                   0.61    overstock

Pricing & Discounts

In [63]:
#What is the impact of discount_percent on units_sold?
pd.read_sql("""
select 
    case 
        when discount_percent between 0 and 10 then '0-10'
        when discount_percent between 11 and 20 then '11-20'
        when discount_percent between 21 and 30 then '21-30'
        else '30+'
    end as discount_bucket,
    avg(units_sold) as avg_units_sold
from orders o
join products p
    on o.product_id = p.product_id
group by discount_bucket
order by discount_bucket;
""", con=engine)

  discount_bucket  avg_units_sold
0            0-10        2,510.70
1           11-20        2,497.28
2           21-30        2,504.08
3             30+        2,514.61

In [64]:
#Do higher discounts lead to higher sales?
pd.read_sql("""
select 
    o.discount_percent,
    avg(o.units_sold) as avg_units_sold
from orders o
join products p
    on o.product_id = p.product_id
group by o.discount_percent
order by o.discount_percent;
    
""", con=engine)

   discount_percent  avg_units_sold
0                 0        2,532.59
1                 5        2,519.56
2                10        2,480.26
3                15        2,510.91
4                20        2,483.73
5                30        2,504.08
6                40        2,506.95
7                50        2,522.36

In [70]:
#Which products have high discounts but low sales?
pd.read_sql("""
select 
    a.product_name as name,
    sum(b.units_sold * b.price) as sales,
    avg(b.discount_percent) as discount_percent
from orders b
join products a
    on a.product_id = b.product_id
group by a.product_name, a.product_id
having avg(b.discount_percent) > 20
order by discount_percent desc,
sales asc
limit 10;
""", con=engine)

                   name     sales  discount_percent
0        LG Edition 518      0.00             50.00
1      Reebok Prime 856      0.00             50.00
2        Sony Model 761      0.00             50.00
3          LG Ultra 740 11,475.80             50.00
4      Reebok Prime 255 18,128.40             50.00
5    Philips Series 533 21,471.08             50.00
6       Boat Series 346 22,105.30             50.00
7       Apple Model 411 28,710.24             50.00
8        Boat Ultra 747 45,945.17             50.00
9  Whirlpool Series 990 48,327.11             50.00

In [72]:
#What is the average discount by category?
pd.read_sql("""
select 
    a.category,
    avg(b.discount_percent) as discount_percent
from orders b
join products a
    on a.product_id = b.product_id
group by a.category
order by discount_percent desc
limit 10;
""", con=engine)

         category  discount_percent
0            Toys             21.48
1         Mobiles             21.47
2     Electronics             21.43
3      Appliances             21.38
4  Home & Kitchen             21.35
5          Beauty             21.32
6         Fashion             21.23
7          Sports             21.15

Customer Behavior

In [75]:
#What is the relationship between rating and units_sold?
pd.read_sql("""
select 
    r.rating,
    sum(o.units_sold) as total_units_sold
from orders o
join reviews r
    on o.product_id = r.product_id
group by r.rating
order by r.rating
limit 10;
""", con=engine)

   rating  total_units_sold
0    1.00      2,511,991.00
1    1.10      5,401,175.00
2    1.20      4,954,175.00
3    1.30      4,956,131.00
4    1.40      4,883,361.00
5    1.50      5,078,712.00
6    1.60      5,073,397.00
7    1.70      4,800,628.00
8    1.80      5,076,999.00
9    1.90      4,916,400.00

In [76]:
#Do products with more reviews sell more?
pd.read_sql("""
select 
    case 
        when r.review_count < 10 then 'low'
        when r.review_count between 10 and 50 then 'medium'
        else 'high'
    end as review_bucket,
    avg(o.units_sold) as avg_units_sold
from orders o
join reviews r
    on o.product_id = r.product_id
group by review_bucket
order by avg_units_sold;
""", con=engine)

  review_bucket  avg_units_sold
0           low        2,429.71
1          high        2,507.44
2        medium        2,603.51

In [77]:
#Which products have high ratings but low sales?
pd.read_sql("""
select 
    p.product_name,
    avg(r.rating) as rating,
    sum(o.units_sold * o.price) as sales
from orders o
join products p on p.product_id = o.product_id
join reviews r on r.product_id = p.product_id
group by p.product_name, p.product_id
having avg(r.rating) >= 4
order by sales asc
limit 10;
""", con=engine)

            product_name  rating     sales
0  Whirlpool Edition 438    4.60      0.00
1    Prestige Series 683    4.50      0.00
2        Boat Series 933    4.20      0.00
3         LG Edition 518    4.20      0.00
4        Boat Series 416    4.30      0.00
5         Sony Prime 634    4.00  8,044.46
6        Redmi Prime 245    4.60 10,120.38
7       Adidas Model 886    4.60 11,495.46
8       Reebok Prime 458    5.00 18,016.14
9     Philips Series 533    4.60 21,471.08

In [78]:
#Which products have low ratings but high sales?
pd.read_sql("""
select 
    p.product_name,
    avg(r.rating) as rating,
    sum(o.units_sold * o.price) as sales
from orders o
join products p on p.product_id = o.product_id
join reviews r on r.product_id = p.product_id
group by p.product_name, p.product_id
having avg(r.rating) < 3
order by sales desc
limit 10;
""", con=engine)

          product_name  rating          sales
0      Nike Series 426    1.40 296,405,801.12
1   Reebok Edition 610    1.40 295,594,119.35
2         LG Model 822    2.70 295,082,798.92
3       Nike Model 696    2.70 294,335,083.89
4     Apple Series 355    1.60 294,281,137.17
5  Whirlpool Ultra 331    1.20 293,217,518.10
6  Whirlpool Prime 534    1.40 292,967,469.95
7       LG Edition 280    1.10 292,668,399.26
8     Puma Edition 217    2.70 292,522,284.90
9    Reebok Series 194    2.80 292,351,621.65

In [80]:
#What is the average rating per category/brand?
pd.read_sql("""
select 
    p.brand,
    avg(r.rating) as avg_rating
from reviews r
join products p
    on p.product_id = r.product_id
group by p.brand
order by avg_rating desc;
""", con=engine)

        brand  avg_rating
0        Sony        3.02
1     Samsung        3.02
2        Nike        3.01
3      Adidas        3.01
4          LG        3.00
5       Redmi        3.00
6       Apple        3.00
7   Whirlpool        3.00
8    Prestige        3.00
9     Philips        3.00
10       Puma        3.00
11       Boat        2.99
12         HP        2.99
13       Dell        2.99
14     Reebok        2.98

Delivery Analysis

In [81]:
#Does delivery_days affect units_sold?
pd.read_sql("""
select 
    l.delivery_days,
    avg(o.units_sold) as avg_units_sold
from orders o
join logistics l
    on o.product_id = l.product_id
group by l.delivery_days
order by l.delivery_days;
""", con=engine)

    delivery_days  avg_units_sold
0               1        2,512.58
1               2        2,503.91
2               3        2,479.24
3               4        2,538.52
4               5        2,488.24
5               6        2,517.23
6               7        2,518.41
7               8        2,492.81
8               9        2,495.23
9              10        2,505.93
10             11        2,529.87

In [83]:
#Which products have the fastest vs slowest delivery?
pd.read_sql("""
select 
    p.product_name,
    l.delivery_days
from logistics l
join products p
    on p.product_id = l.product_id
order by l.delivery_days asc
limit 10;
""", con=engine)

          product_name  delivery_days
0      Apple Model 380              1
1      Redmi Model 367              1
2  Whirlpool Ultra 144              1
3        HP Series 515              1
4     Redmi Series 977              1
5    Samsung Prime 997              1
6       Sony Ultra 663              1
7     Dell Edition 703              1
8     Redmi Series 878              1
9    Redmi Edition 984              1

In [84]:
#Which cities have longer delivery times?
pd.read_sql("""
select 
    s.seller_city,
    avg(l.delivery_days) as avg_delivery_days
from logistics l
join orders o
    on o.product_id = l.product_id
join sellers s
    on s.seller = o.seller
group by s.seller_city
order by avg_delivery_days desc;
""", con=engine)

  seller_city  avg_delivery_days
0     Chennai               6.01
1   Hyderabad               6.01
2      Mumbai               6.01
3   Bengaluru               6.01
4       Delhi               6.01
5        Pune               6.01
6     Kolkata               6.01
7   Ahmedabad               6.01

In [85]:
#Do faster deliveries lead to higher sales?
pd.read_sql("""
select 
    l.delivery_days,
    sum(o.units_sold) as total_units_sold
from orders o
join logistics l
    on o.product_id = l.product_id
group by l.delivery_days
order by l.delivery_days;
""", con=engine)

    delivery_days  total_units_sold
0               1     18,560,463.00
1               2     17,572,470.00
2               3     17,981,905.00
3               4     18,587,030.00
4               5     18,161,685.00
5               6     18,249,885.00
6               7     18,621,115.00
7               8     18,092,809.00
8               9     18,142,833.00
9              10     18,163,012.00
10             11     18,468,055.00

Returns & Policies

In [90]:
#Do returnable products sell more than non-returnable ones?
pd.read_sql("""
select 
    r.is_returnable,
    sum(o.units_sold) as total_units_sold
from orders o
join returns r
    on o.product_id = r.product_id
group by r.is_returnable;
""", con=engine)

   is_returnable  total_units_sold
0              1    160,643,379.00
1              0     39,957,883.00

In [91]:
#Which categories have higher return_policy_days?
pd.read_sql("""
select 
    p.category,
    avg(r.return_policy_days) as avg_return_days
from returns r
join products p
    on p.product_id = r.product_id
group by p.category
order by avg_return_days desc;
""", con=engine)

         category  avg_return_days
0          Sports            12.52
1         Mobiles            12.41
2            Toys            12.41
3      Appliances            12.38
4  Home & Kitchen            12.33
5         Fashion            12.32
6          Beauty            12.27
7     Electronics            12.25

In [92]:
#Is there a relationship between return_policy_days and sales?
pd.read_sql("""
select 
    r.return_policy_days,
    sum(o.units_sold) as total_units_sold
from orders o
join returns r
    on o.product_id = r.product_id
group by r.return_policy_days
order by r.return_policy_days;
""", con=engine)

   return_policy_days  total_units_sold
0                   0     39,957,883.00
1                   7     40,328,012.00
2                  10     40,536,489.00
3                  15     40,373,574.00
4                  30     39,405,304.00

In [110]:
#Are highly sold products more likely to be returnable?
pd.read_sql("""
select 
    p.category,
    r.is_returnable,
    avg(t.total_units_sold) as avg_units_sold
from (
    select product_id, sum(units_sold) as total_units_sold
    from orders
    group by product_id
) t
join returns r on r.product_id = t.product_id
join products p on p.product_id = t.product_id
group by p.category, r.is_returnable
order by p.category;
""", con=engine)

          category  is_returnable  avg_units_sold
0       Appliances              0        2,555.26
1       Appliances              1        2,518.46
2           Beauty              0        2,433.01
3           Beauty              1        2,504.05
4      Electronics              0        2,547.59
5      Electronics              1        2,518.07
6          Fashion              0        2,497.20
7          Fashion              1        2,498.55
8   Home & Kitchen              0        2,480.83
9   Home & Kitchen              1        2,537.63
10         Mobiles              0        2,482.95
11         Mobiles              1        2,497.90
12          Sports              0        2,504.24
13          Sports              1        2,477.79
14            Toys              0        2,520.99
15            Toys              1        2,517.98

Brand Performance

In [94]:
#Which brands generate the highest revenue?
pd.read_sql("""
select 
    p.brand,
    sum(o.units_sold * o.price) as revenue
from orders o
join products p
    on p.product_id = o.product_id
group by p.brand
order by revenue desc;
""", con=engine)

        brand            revenue
0        Nike 411,972,044,355.89
1       Apple 409,091,636,392.18
2        Puma 407,795,349,591.31
3      Adidas 407,780,150,157.20
4        Boat 406,618,616,565.19
5          LG 404,920,821,747.62
6          HP 404,206,224,610.54
7    Prestige 404,177,056,613.52
8      Reebok 403,507,600,204.85
9        Dell 401,919,259,512.24
10    Samsung 401,389,498,184.29
11      Redmi 400,209,313,257.56
12  Whirlpool 397,922,044,754.79
13    Philips 397,354,324,778.27
14       Sony 394,794,753,416.05

In [95]:
#Which brands sell the most units?
pd.read_sql("""
select 
    p.brand,
    sum(o.units_sold) as total_units
from orders o
join products p
    on p.product_id = o.product_id
group by p.brand
order by total_units desc;
""", con=engine)

        brand   total_units
0        Nike 13,569,204.00
1      Reebok 13,507,145.00
2    Prestige 13,497,983.00
3      Adidas 13,459,726.00
4        Puma 13,443,146.00
5       Apple 13,425,297.00
6        Dell 13,415,026.00
7          LG 13,403,447.00
8          HP 13,356,680.00
9       Redmi 13,320,362.00
10    Samsung 13,303,391.00
11       Boat 13,296,314.00
12  Whirlpool 13,244,034.00
13    Philips 13,229,419.00
14       Sony 13,130,088.00

In [96]:
#Which brands have the highest average ratings?
pd.read_sql("""
select 
    p.brand,
    avg(r.rating) as avg_rating
from reviews r
join products p
    on p.product_id = r.product_id
group by p.brand
order by avg_rating desc;
""", con=engine)

        brand  avg_rating
0        Sony        3.02
1     Samsung        3.02
2        Nike        3.01
3      Adidas        3.01
4          LG        3.00
5       Redmi        3.00
6       Apple        3.00
7   Whirlpool        3.00
8    Prestige        3.00
9     Philips        3.00
10       Puma        3.00
11       Boat        2.99
12         HP        2.99
13       Dell        2.99
14     Reebok        2.98

In [105]:
#Which brands underperform despite high ratings?
pd.read_sql("""
select 
    p.brand,
    avg(r.rating) as avg_rating,
    sum(o.units_sold * o.price) as revenue
from products p
join reviews r on p.product_id = r.product_id
join orders o on o.product_id = p.product_id
group by p.brand
order by avg_rating desc, revenue asc
limit 10;
""", con=engine)

       brand  avg_rating            revenue
0       Sony        3.02 394,794,753,416.05
1    Samsung        3.02 401,389,498,184.29
2       Nike        3.01 411,972,044,355.89
3     Adidas        3.01 407,780,150,157.20
4         LG        3.00 404,920,821,747.62
5      Redmi        3.00 400,209,313,257.56
6      Apple        3.00 409,091,636,392.18
7  Whirlpool        3.00 397,922,044,754.79
8   Prestige        3.00 404,177,056,613.52
9    Philips        3.00 397,354,324,778.27

Time-Based Analysis

In [103]:
#How do newly listed products perform vs older ones?
pd.read_sql("""
select 
    case 
        when o.listing_date >= date_sub((select max(listing_date) from orders), interval 30 day) then 'new'
        when o.listing_date >= date_sub((select max(listing_date) from orders), interval 90 day) then 'mid'
        else 'old'
    end as product_age,
    avg(o.units_sold) as avg_units_sold,
    avg(o.units_sold * o.price) as avg_revenue
from orders o
group by product_age;
""", con=engine)

  product_age  avg_units_sold   avg_revenue
0         old        2,507.12 75,628,482.06
1         mid        2,491.85 75,646,724.52
2         new        2,560.39 78,243,331.81

In [99]:
#Is there a trend in product listings over time?
pd.read_sql("""
select 
    date_format(o.listing_date, '%%Y-%%m') as month,
    count(distinct o.product_id) as products_listed
from orders o
group by date_format(o.listing_date, '%%Y-%%m')
order by month;
""", con=engine)

      month  products_listed
0   2018-01             1237
1   2018-02             1114
2   2018-03             1176
3   2018-04             1191
4   2018-05             1275
..      ...              ...
61  2023-02             1133
62  2023-03             1312
63  2023-04             1186
64  2023-05             1250
65  2023-06              999

[66 rows x 2 columns]

In [106]:
#Do older products have more reviews and sales?
pd.read_sql("""
select 
    case 
        when o.listing_date < date_sub((select max(listing_date) from orders), interval 90 day) then 'old'
        else 'new'
    end as product_age,
    avg(r.review_count) as avg_reviews,
    avg(o.units_sold) as avg_units_sold
from orders o
join reviews r
    on r.product_id = o.product_id
group by product_age;
""", con=engine)

  product_age  avg_reviews  avg_units_sold
0         old    25,105.87        2,507.12
1         new    25,026.77        2,515.71